name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Flag Check
      id: flag-check
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Flag Check
        setup-command: ''
        command: "bash script.sh"
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FLAG-CHECK_RESULTS: "${{steps.flag-check.outputs.result}}"
      with:
        runners: flag-check
